drop database if exists aparat;

create database aparat;
use aparat;

create table ap_1 (Dt integer unsigned not null,
Opr smallint default '0',
Vias smallint default '0',
Lev smallint default '0',
Vak smallint default '0',
Temp smallint default '0',
Rr smallint default '0',
Mr smallint default '0',
Status smallint default '0',
sirup smallint default '0',
sirup_r smallint default '0',
bila smallint default '0',
bila_r smallint default '0',
voda smallint default '0',
voda_R smallint default '0',
para smallint default '0',
para_r smallint default '0',
vakume_r smallint default '0',
zatrav smallint default '0',
zatrav_r smallint default '0',
ai smallint default '0',
dio smallint default '0',
mmi smallint default '0',
km smallint default '0',
Tall smallint default '0',
Page smallint default '0',
primary key(Dt)) Engine=InnoDb;

create table ap_2 (Dt integer unsigned not null,
Opr smallint default '0',
Vias smallint default '0',
Lev smallint default '0',
Vak smallint default '0',
Temp smallint default '0',
Rr smallint default '0',
Mr smallint default '0',
Status smallint default '0',
sirup smallint default '0',
sirup_r smallint default '0',
bila smallint default '0',
bila_r smallint default '0',
voda smallint default '0',
voda_R smallint default '0',
para smallint default '0',
para_r smallint default '0',
vakume_r smallint default '0',
zatrav smallint default '0',
zatrav_r smallint default '0',
ai smallint default '0',
dio smallint default '0',
mmi smallint default '0',
km smallint default '0',
Tall smallint default '0',
Page smallint default '0',
primary key(Dt)) Engine=InnoDb;

create table ap_3 (Dt integer unsigned not null,
Opr smallint default '0',
Vias smallint default '0',
Lev smallint default '0',
Vak smallint default '0',
Temp smallint default '0',
Rr smallint default '0',
Mr smallint default '0',
Status smallint default '0',
sirup smallint default '0',
sirup_r smallint default '0',
bila smallint default '0',
bila_r smallint default '0',
voda smallint default '0',
voda_R smallint default '0',
para smallint default '0',
para_r smallint default '0',
vakume_r smallint default '0',
zatrav smallint default '0',
zatrav_r smallint default '0',
ai smallint default '0',
dio smallint default '0',
mmi smallint default '0',
km smallint default '0',
Tall smallint default '0',
Page smallint default '0',
primary key(Dt)) Engine=InnoDb;


create table trend (Dt integer unsigned not null,
h_1 smallint default '0',
h_2 smallint default '0',
h_3 smallint default '0',
L_1 smallint default '0',
L_2 smallint default '0',
L_3 smallint default '0',
L_4 smallint default '0',
L_5 smallint default '0',
T_1 smallint default '0',
T_2 smallint default '0',
T_3 smallint default '0',
T_4 smallint default '0',
T_5 smallint default '0',
T_6 smallint default '0',
primary key(Dt)) Engine=InnoDb;

grant INSERT,SELECT,UPDATE,DELETE on aparat.* to 'scada'@'%';
